apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "7070"
    spec:
      containers:
        - name: product-service
          image: product-service:v5
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 7070
          env:
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://app-postgres/product_db
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://app-postgres/product_db
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service