spring:
  application:
    name: product-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/product_db
    pool:
      max-size: 10
      initial-size: 5
      max-create-connection-time: 2s
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/product_db
server:
  port: 7070
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

