apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-service
  labels:
    app: aggregator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-service
  template:
    metadata:
      labels:
        app: aggregator-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: aggregator-service
          image: aggregator-service:v4
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8080
          env:
            - name: APP_CUSTOMER_SERVICE_URI
              value: http://customer-service
            - name: APP_PRODUCT_SERVICE_URI
              value: http://product-service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
