spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BOURGUI07/flash-sale-config
          default-label: main
          search-paths:
            - /{application}
          timeout: 5
          clone-on-start: true
          force-pull: true

server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always